"""
registry.py — AUTO-GENERATED by config/generate.py
DO NOT EDIT MANUALLY. Edit config/workflow_config.json and re-run generate.py.
"""

from __future__ import annotations

import os
from typing import Any


# ---------------------------------------------------------------------------
# Step configuration
# ---------------------------------------------------------------------------

STEP_CONFIG: dict[str, dict[str, Any]] = {
    "STEP_00": {
        "name": "Scenario Builder",
        "description": "Parse MISMO XML, loan profile JSON, and submitted documents into scenario_summary; detect missing variables and contradictions; route docs to facets.",
        "plan_file": "step_00_scenario_builder.md",
        "tools": ["parse_loan_file", "parse_loan_profile", "parse_submitted_documents", "build_scenario_summary", "detect_contradictions", "route_to_facets"],
        "substeps": [
                {
                        "id": "0.1",
                        "name": "Parse MISMO XML loan file",
                        "tools": [
                                "parse_loan_file"
                        ]
                },
                {
                        "id": "0.2",
                        "name": "Parse loan profile JSON",
                        "tools": [
                                "parse_loan_profile"
                        ]
                },
                {
                        "id": "0.2b",
                        "name": "Parse submitted documents",
                        "tools": [
                                "parse_submitted_documents"
                        ]
                },
                {
                        "id": "0.3",
                        "name": "Build scenario summary and detect contradictions",
                        "tools": [
                                "build_scenario_summary",
                                "detect_contradictions"
                        ]
                },
                {
                        "id": "0.4",
                        "name": "Route docs to facets",
                        "tools": [
                                "route_to_facets"
                        ]
                },
                {
                        "id": "0.5",
                        "name": "Save step report",
                        "tools": [
                                "save_step_report"
                        ]
                }
        ],
    },
    "STEP_00b": {
        "name": "Submission Document Completeness Check",
        "description": "Deterministic check of whether required submission documents are present based on transaction type and income doc type.",
        "plan_file": "step_00b_doc_completeness.md",
        "tools": ["check_submission_completeness"],
        "substeps": [
                {
                        "id": "0b.1",
                        "name": "Check submission completeness",
                        "tools": [
                                "check_submission_completeness"
                        ]
                },
                {
                        "id": "0b.2",
                        "name": "Save step report",
                        "tools": [
                                "save_step_report"
                        ]
                }
        ],
    },
    "STEP_01": {
        "name": "Cross-Cutting Gatekeeper",
        "description": "Generate cross-cutting conditions: missing core variables, contradictions, overlay conflicts, universal compliance prerequisites.",
        "plan_file": "step_01_cross_cutting.md",
        "tools": ["check_overlay_conflicts", "generate_crosscutting_conditions"],
        "substeps": [
                {
                        "id": "1.1",
                        "name": "Check overlay conflicts",
                        "tools": [
                                "check_overlay_conflicts"
                        ]
                },
                {
                        "id": "1.2",
                        "name": "Generate cross-cutting conditions",
                        "tools": [
                                "generate_crosscutting_conditions"
                        ]
                },
                {
                        "id": "1.3",
                        "name": "Save step report",
                        "tools": [
                                "save_step_report"
                        ]
                }
        ],
    },
    "STEP_02": {
        "name": "Income Conditions Engine",
        "description": "Generate income-only conditions for W2, self-employed, bank statement, retirement, rental, DSCR, etc.",
        "plan_file": "step_02_income.md",
        "tools": ["load_guideline_sections", "generate_income_conditions"],
        "substeps": [
                {
                        "id": "2.1",
                        "name": "Load income guideline sections",
                        "tools": [
                                "load_guideline_sections"
                        ]
                },
                {
                        "id": "2.2",
                        "name": "Generate income conditions",
                        "tools": [
                                "generate_income_conditions"
                        ]
                },
                {
                        "id": "2.3",
                        "name": "Save step report",
                        "tools": [
                                "save_step_report"
                        ]
                }
        ],
    },
    "STEP_03": {
        "name": "Assets Conditions Engine",
        "description": "Generate conditions for assets, funds to close, and reserves.",
        "plan_file": "step_03_assets.md",
        "tools": ["load_guideline_sections", "generate_asset_conditions"],
        "substeps": [
                {
                        "id": "3.1",
                        "name": "Load assets guideline sections",
                        "tools": [
                                "load_guideline_sections"
                        ]
                },
                {
                        "id": "3.2",
                        "name": "Generate asset conditions",
                        "tools": [
                                "generate_asset_conditions"
                        ]
                },
                {
                        "id": "3.3",
                        "name": "Save step report",
                        "tools": [
                                "save_step_report"
                        ]
                }
        ],
    },
    "STEP_04": {
        "name": "Credit Conditions Engine",
        "description": "Generate credit-only conditions covering report completeness, housing history, bankruptcy, etc.",
        "plan_file": "step_04_credit.md",
        "tools": ["load_guideline_sections", "generate_credit_conditions"],
        "substeps": [
                {
                        "id": "4.1",
                        "name": "Load credit guideline sections",
                        "tools": [
                                "load_guideline_sections"
                        ]
                },
                {
                        "id": "4.2",
                        "name": "Generate credit conditions",
                        "tools": [
                                "generate_credit_conditions"
                        ]
                },
                {
                        "id": "4.3",
                        "name": "Save step report",
                        "tools": [
                                "save_step_report"
                        ]
                }
        ],
    },
    "STEP_05": {
        "name": "Property and Appraisal Conditions Engine",
        "description": "Generate conditions for subject property and appraisal requirements.",
        "plan_file": "step_05_property_appraisal.md",
        "tools": ["load_guideline_sections", "generate_property_conditions"],
        "substeps": [
                {
                        "id": "5.1",
                        "name": "Load property guideline sections",
                        "tools": [
                                "load_guideline_sections"
                        ]
                },
                {
                        "id": "5.2",
                        "name": "Generate property and appraisal conditions",
                        "tools": [
                                "generate_property_conditions"
                        ]
                },
                {
                        "id": "5.3",
                        "name": "Save step report",
                        "tools": [
                                "save_step_report"
                        ]
                }
        ],
    },
    "STEP_06": {
        "name": "Title and Closing Conditions Engine",
        "description": "Generate conditions for title, escrow, payoffs, and closing.",
        "plan_file": "step_06_title_closing.md",
        "tools": ["load_guideline_sections", "generate_title_conditions"],
        "substeps": [
                {
                        "id": "6.1",
                        "name": "Load title guideline sections",
                        "tools": [
                                "load_guideline_sections"
                        ]
                },
                {
                        "id": "6.2",
                        "name": "Generate title and closing conditions",
                        "tools": [
                                "generate_title_conditions"
                        ]
                },
                {
                        "id": "6.3",
                        "name": "Save step report",
                        "tools": [
                                "save_step_report"
                        ]
                }
        ],
    },
    "STEP_07": {
        "name": "Compliance Conditions Engine",
        "description": "Generate conditions for compliance, disclosures, and affidavits.",
        "plan_file": "step_07_compliance.md",
        "tools": ["load_guideline_sections", "generate_compliance_conditions"],
        "substeps": [
                {
                        "id": "7.1",
                        "name": "Load compliance guideline sections",
                        "tools": [
                                "load_guideline_sections"
                        ]
                },
                {
                        "id": "7.2",
                        "name": "Generate compliance conditions",
                        "tools": [
                                "generate_compliance_conditions"
                        ]
                },
                {
                        "id": "7.3",
                        "name": "Save step report",
                        "tools": [
                                "save_step_report"
                        ]
                }
        ],
    },
    "STEP_08": {
        "name": "Program Matrix Eligibility Check",
        "description": "Load the program-specific matrix from program_matrices.md and verify the loan meets LTV/FICO grid, geographic, borrower, property, and DTI eligibility requirements.",
        "plan_file": "step_08_program_eligibility.md",
        "tools": ["check_matrix_eligibility", "load_program_matrix", "generate_matrix_conditions"],
        "substeps": [
                {
                        "id": "8.1",
                        "name": "Run deterministic matrix checks",
                        "tools": [
                                "check_matrix_eligibility"
                        ]
                },
                {
                        "id": "8.2",
                        "name": "Load trimmed matrix for LLM review",
                        "tools": [
                                "load_program_matrix"
                        ]
                },
                {
                        "id": "8.3",
                        "name": "Generate additional matrix conditions",
                        "tools": [
                                "generate_matrix_conditions"
                        ]
                },
                {
                        "id": "8.4",
                        "name": "Save step report",
                        "tools": [
                                "save_step_report"
                        ]
                }
        ],
    },
    "STEP_09": {
        "name": "Merger and Ranker",
        "description": "Merge outputs from modules 01-08; de-duplicate, resolve conflicts, rank, and output final JSON.",
        "plan_file": "step_09_merger_ranker.md",
        "tools": ["merge_conditions", "rank_conditions", "generate_final_output"],
        "substeps": [
                {
                        "id": "9.1",
                        "name": "Merge and de-duplicate conditions",
                        "tools": [
                                "merge_conditions"
                        ]
                },
                {
                        "id": "9.2",
                        "name": "Rank conditions",
                        "tools": [
                                "rank_conditions"
                        ]
                },
                {
                        "id": "9.3",
                        "name": "Generate final output",
                        "tools": [
                                "generate_final_output"
                        ]
                },
                {
                        "id": "9.4",
                        "name": "Save step report",
                        "tools": [
                                "save_step_report"
                        ]
                }
        ],
    },
}


# ---------------------------------------------------------------------------
# Step ordering (derived from phases)
# ---------------------------------------------------------------------------

STEP_ORDER: list[str] = ["STEP_00", "STEP_00b", "STEP_01", "STEP_02", "STEP_03", "STEP_04", "STEP_05", "STEP_06", "STEP_07", "STEP_08", "STEP_09"]


# ---------------------------------------------------------------------------
# General tools — always available regardless of current step
# ---------------------------------------------------------------------------

GENERAL_TOOL_NAMES: list[str] = ["write_todo", "get_workflow_status", "save_step_report"]


# ---------------------------------------------------------------------------
# Dev mode — controlled by config, env vars, or input state
# ---------------------------------------------------------------------------

_DEFAULT_DEV_MODE: dict[str, Any] = {'enabled': False, 'skip_steps': [], 'cutoff_step': None, 'run_only_substeps': []}


def get_dev_mode(input_state: dict | None = None) -> dict[str, Any]:
    """
    Resolve dev mode config.
    Priority: input_state > env vars > config defaults.
    """
    mode = dict(_DEFAULT_DEV_MODE)

    # Override from environment variables
    if os.environ.get("DEV_MODE_ENABLED", "").lower() in ("1", "true", "yes"):
        mode["enabled"] = True
    if os.environ.get("DEV_MODE_SKIP_STEPS"):
        mode["skip_steps"] = os.environ["DEV_MODE_SKIP_STEPS"].split(",")
    if os.environ.get("DEV_MODE_CUTOFF_STEP"):
        mode["cutoff_step"] = os.environ["DEV_MODE_CUTOFF_STEP"]

    # Override from input state (highest priority)
    if input_state:
        state_dev = input_state.get("dev_mode") or {}
        mode.update(state_dev)

    return mode


def is_step_skipped(step_id: str, input_state: dict | None = None) -> bool:
    """Return True if this step should be skipped in dev mode."""
    dev = get_dev_mode(input_state)
    if not dev.get("enabled"):
        return False
    if step_id in (dev.get("skip_steps") or []):
        return True
    cutoff = dev.get("cutoff_step")
    if cutoff and STEP_ORDER.index(step_id) > STEP_ORDER.index(cutoff):
        return True
    return False


def get_step_tools(step_id: str) -> list[str]:
    """Return the tool names registered for a given step."""
    return STEP_CONFIG.get(step_id, {}).get("tools", [])


def get_step_plan_file(step_id: str) -> str | None:
    """Return the plan markdown filename for a given step."""
    return STEP_CONFIG.get(step_id, {}).get("plan_file")


def get_current_step(state: dict) -> str | None:
    """Extract the current step from agent state."""
    return state.get("current_step")
