"""
registry.py — AUTO-GENERATED by config/generate.py
DO NOT EDIT MANUALLY. Edit config/workflow_config.json and re-run generate.py.
"""

from __future__ import annotations

import os
from typing import Any


# ---------------------------------------------------------------------------
# Step configuration
# ---------------------------------------------------------------------------

STEP_CONFIG: dict[str, dict[str, Any]] = {
    "STEP_00": {
        "name": "Scenario Builder",
        "description": "Parse MISMO XML, manifest documents, and eligibility output into scenario_summary; detect missing variables and contradictions; build document inventory; route docs and overlays to facets.",
        "plan_file": "step_00_scenario_builder.md",
        "tools": ["parse_loan_file", "parse_manifest_documents", "parse_eligibility_output", "load_doctype_masterlist", "build_scenario_summary", "detect_contradictions", "route_to_facets"],
        "substeps": [
                {
                        "id": "0.1",
                        "name": "Parse MISMO XML loan file",
                        "tools": [
                                "parse_loan_file"
                        ]
                },
                {
                        "id": "0.2",
                        "name": "Parse manifest documents",
                        "tools": [
                                "parse_manifest_documents"
                        ]
                },
                {
                        "id": "0.3",
                        "name": "Parse eligibility engine output",
                        "tools": [
                                "parse_eligibility_output"
                        ]
                },
                {
                        "id": "0.4",
                        "name": "Load doctype masterlist",
                        "tools": [
                                "load_doctype_masterlist"
                        ]
                },
                {
                        "id": "0.5",
                        "name": "Build scenario summary and detect contradictions",
                        "tools": [
                                "build_scenario_summary",
                                "detect_contradictions"
                        ]
                },
                {
                        "id": "0.6",
                        "name": "Route docs and overlays to facets",
                        "tools": [
                                "route_to_facets"
                        ]
                },
                {
                        "id": "0.7",
                        "name": "Save step report",
                        "tools": [
                                "save_step_report"
                        ]
                }
        ],
    },
    "STEP_01": {
        "name": "Cross-Cutting Document Needs Gatekeeper",
        "description": "Generate document requests for missing core variables, contradictions, overlay conflicts, and file-wide blockers.",
        "plan_file": "step_01_cross_cutting.md",
        "tools": ["load_guideline_sections", "check_overlay_conflicts", "generate_crosscutting_document_requests"],
        "substeps": [
                {
                        "id": "1.1",
                        "name": "Load cross-cutting guideline sections",
                        "tools": [
                                "load_guideline_sections"
                        ]
                },
                {
                        "id": "1.2",
                        "name": "Check overlay conflicts",
                        "tools": [
                                "check_overlay_conflicts"
                        ]
                },
                {
                        "id": "1.3",
                        "name": "Generate cross-cutting document requests",
                        "tools": [
                                "generate_crosscutting_document_requests"
                        ]
                },
                {
                        "id": "1.4",
                        "name": "Save step report",
                        "tools": [
                                "save_step_report"
                        ]
                }
        ],
    },
    "STEP_02": {
        "name": "Income Document Needs Engine",
        "description": "Generate document requests for income qualification, calculation, stability, and documentation.",
        "plan_file": "step_02_income.md",
        "tools": ["load_guideline_sections", "generate_income_document_requests"],
        "substeps": [
                {
                        "id": "2.1",
                        "name": "Load income guideline sections",
                        "tools": [
                                "load_guideline_sections"
                        ]
                },
                {
                        "id": "2.2",
                        "name": "Generate income document requests",
                        "tools": [
                                "generate_income_document_requests"
                        ]
                },
                {
                        "id": "2.3",
                        "name": "Save step report",
                        "tools": [
                                "save_step_report"
                        ]
                }
        ],
    },
    "STEP_03": {
        "name": "Assets Document Needs Engine",
        "description": "Generate document requests for funds to close, reserves, gifts, large deposits, sourcing, and asset ownership.",
        "plan_file": "step_03_assets.md",
        "tools": ["load_guideline_sections", "generate_asset_document_requests"],
        "substeps": [
                {
                        "id": "3.1",
                        "name": "Load assets guideline sections",
                        "tools": [
                                "load_guideline_sections"
                        ]
                },
                {
                        "id": "3.2",
                        "name": "Generate asset document requests",
                        "tools": [
                                "generate_asset_document_requests"
                        ]
                },
                {
                        "id": "3.3",
                        "name": "Save step report",
                        "tools": [
                                "save_step_report"
                        ]
                }
        ],
    },
    "STEP_04": {
        "name": "Credit Document Needs Engine",
        "description": "Generate document requests for credit report completeness, scores, tradelines, housing history, inquiries, disputes, and credit events.",
        "plan_file": "step_04_credit.md",
        "tools": ["load_guideline_sections", "generate_credit_document_requests"],
        "substeps": [
                {
                        "id": "4.1",
                        "name": "Load credit guideline sections",
                        "tools": [
                                "load_guideline_sections"
                        ]
                },
                {
                        "id": "4.2",
                        "name": "Generate credit document requests",
                        "tools": [
                                "generate_credit_document_requests"
                        ]
                },
                {
                        "id": "4.3",
                        "name": "Save step report",
                        "tools": [
                                "save_step_report"
                        ]
                }
        ],
    },
    "STEP_05": {
        "name": "Property and Appraisal Document Needs Engine",
        "description": "Generate document requests for appraisal, valuation, property type, LTV support, rent schedule, condo/PUD, inspections, and flood/property eligibility.",
        "plan_file": "step_05_property_appraisal.md",
        "tools": ["load_guideline_sections", "generate_property_document_requests"],
        "substeps": [
                {
                        "id": "5.1",
                        "name": "Load property guideline sections",
                        "tools": [
                                "load_guideline_sections"
                        ]
                },
                {
                        "id": "5.2",
                        "name": "Generate property document requests",
                        "tools": [
                                "generate_property_document_requests"
                        ]
                },
                {
                        "id": "5.3",
                        "name": "Save step report",
                        "tools": [
                                "save_step_report"
                        ]
                }
        ],
    },
    "STEP_06": {
        "name": "Title and Closing Document Needs Engine",
        "description": "Generate document requests for title, vesting, lien position, payoff, escrow, insurance, taxes, closing disclosure, and settlement support.",
        "plan_file": "step_06_title_closing.md",
        "tools": ["load_guideline_sections", "generate_title_document_requests"],
        "substeps": [
                {
                        "id": "6.1",
                        "name": "Load title guideline sections",
                        "tools": [
                                "load_guideline_sections"
                        ]
                },
                {
                        "id": "6.2",
                        "name": "Generate title document requests",
                        "tools": [
                                "generate_title_document_requests"
                        ]
                },
                {
                        "id": "6.3",
                        "name": "Save step report",
                        "tools": [
                                "save_step_report"
                        ]
                }
        ],
    },
    "STEP_07": {
        "name": "Compliance Document Needs Engine",
        "description": "Generate document requests for authorizations, affidavits, occupancy certifications, business purpose, ITIN support, identity, trust/entity docs.",
        "plan_file": "step_07_compliance.md",
        "tools": ["load_guideline_sections", "generate_compliance_document_requests"],
        "substeps": [
                {
                        "id": "7.1",
                        "name": "Load compliance guideline sections",
                        "tools": [
                                "load_guideline_sections"
                        ]
                },
                {
                        "id": "7.2",
                        "name": "Generate compliance document requests",
                        "tools": [
                                "generate_compliance_document_requests"
                        ]
                },
                {
                        "id": "7.3",
                        "name": "Save step report",
                        "tools": [
                                "save_step_report"
                        ]
                }
        ],
    },
    "STEP_08": {
        "name": "Document Request Merger and Ranker",
        "description": "Merge document requests from modules 01-07; aggregate specifications and reasons; de-duplicate; rank; produce final Predictive Document Needs List.",
        "plan_file": "step_08_merger_ranker.md",
        "tools": ["merge_document_requests", "rank_document_requests", "generate_final_output"],
        "substeps": [
                {
                        "id": "8.1",
                        "name": "Merge and de-duplicate document requests",
                        "tools": [
                                "merge_document_requests"
                        ]
                },
                {
                        "id": "8.2",
                        "name": "Rank document requests",
                        "tools": [
                                "rank_document_requests"
                        ]
                },
                {
                        "id": "8.3",
                        "name": "Generate final output",
                        "tools": [
                                "generate_final_output"
                        ]
                },
                {
                        "id": "8.4",
                        "name": "Save step report",
                        "tools": [
                                "save_step_report"
                        ]
                }
        ],
    },
}


# ---------------------------------------------------------------------------
# Step ordering (derived from phases)
# ---------------------------------------------------------------------------

STEP_ORDER: list[str] = ["STEP_00", "STEP_01", "STEP_02", "STEP_03", "STEP_04", "STEP_05", "STEP_06", "STEP_07", "STEP_08"]


# ---------------------------------------------------------------------------
# General tools — always available regardless of current step
# ---------------------------------------------------------------------------

GENERAL_TOOL_NAMES: list[str] = ["write_todo", "get_workflow_status", "save_step_report"]


# ---------------------------------------------------------------------------
# Dev mode — controlled by config, env vars, or input state
# ---------------------------------------------------------------------------

_DEFAULT_DEV_MODE: dict[str, Any] = {'enabled': False, 'skip_steps': [], 'cutoff_step': None, 'run_only_substeps': []}


def get_dev_mode(input_state: dict | None = None) -> dict[str, Any]:
    """
    Resolve dev mode config.
    Priority: input_state > env vars > config defaults.
    """
    mode = dict(_DEFAULT_DEV_MODE)

    # Override from environment variables
    if os.environ.get("DEV_MODE_ENABLED", "").lower() in ("1", "true", "yes"):
        mode["enabled"] = True
    if os.environ.get("DEV_MODE_SKIP_STEPS"):
        mode["skip_steps"] = os.environ["DEV_MODE_SKIP_STEPS"].split(",")
    if os.environ.get("DEV_MODE_CUTOFF_STEP"):
        mode["cutoff_step"] = os.environ["DEV_MODE_CUTOFF_STEP"]

    # Override from input state (highest priority)
    if input_state:
        state_dev = input_state.get("dev_mode") or {}
        mode.update(state_dev)

    return mode


def is_step_skipped(step_id: str, input_state: dict | None = None) -> bool:
    """Return True if this step should be skipped in dev mode."""
    dev = get_dev_mode(input_state)
    if not dev.get("enabled"):
        return False
    if step_id in (dev.get("skip_steps") or []):
        return True
    cutoff = dev.get("cutoff_step")
    if cutoff and STEP_ORDER.index(step_id) > STEP_ORDER.index(cutoff):
        return True
    return False


def get_step_tools(step_id: str) -> list[str]:
    """Return the tool names registered for a given step."""
    return STEP_CONFIG.get(step_id, {}).get("tools", [])


def get_step_plan_file(step_id: str) -> str | None:
    """Return the plan markdown filename for a given step."""
    return STEP_CONFIG.get(step_id, {}).get("plan_file")


def get_current_step(state: dict) -> str | None:
    """Extract the current step from agent state."""
    return state.get("current_step")
