"""
verify_conditions.py — Compare engine-generated conditions against
underwriter conditions from Encompass using semantic LLM matching.

Usage:
    python verify_conditions.py <engine_output.json> <underwriter_conditions>

    engine_output.json   — Our pipeline output (e.g. emmanuel_output.json)
    underwriter_conditions — Either:
        - A .json file with a list of condition strings or objects
        - A .txt file with one condition per line

Output:
    Prints a summary report and writes verify_report.json with:
        - matched:      pairs where engine ≈ underwriter (with confidence)
        - engine_only:  conditions we generated that the underwriter didn't
        - uw_only:      conditions the underwriter had that we missed
        - stats:        precision, recall, F1, total counts
"""

from __future__ import annotations

import json
import os
import sys
from pathlib import Path

from dotenv import load_dotenv

load_dotenv(Path(__file__).parent / ".env")

from anthropic import Anthropic


def _load_engine_conditions(path: Path) -> list[str]:
    with open(path) as f:
        data = json.load(f)

    conditions = data.get("conditions", [])
    out: list[str] = []
    for c in conditions:
        if isinstance(c, str):
            out.append(c)
        elif isinstance(c, dict):
            title = c.get("title", "")
            desc = c.get("description", "")
            cat = c.get("category", "")
            sev = c.get("severity", "")
            out.append(f"[{sev}/{cat}] {title}: {desc}" if desc else f"[{sev}/{cat}] {title}")
        else:
            out.append(str(c))
    return out


def _load_underwriter_conditions(path: Path) -> list[str]:
    if path.suffix == ".json":
        with open(path) as f:
            data = json.load(f)
        if isinstance(data, list):
            items = data
        elif isinstance(data, dict):
            items = (
                data.get("conditions", [])
                or data.get("items", [])
                or data.get("preliminary_conditions", [])
                or data.get("prior_to_docs", [])
                or list(data.values())[0] if data else []
            )
        else:
            items = [data]

        out: list[str] = []
        for item in items:
            if isinstance(item, str):
                out.append(item)
            elif isinstance(item, dict):
                text = (
                    item.get("description", "")
                    or item.get("text", "")
                    or item.get("condition", "")
                    or item.get("title", "")
                    or item.get("name", "")
                    or str(item)
                )
                out.append(text)
            else:
                out.append(str(item))
        return [c for c in out if c.strip()]

    else:
        text = path.read_text(encoding="utf-8")
        lines = [ln.strip() for ln in text.splitlines() if ln.strip()]
        return lines


_MATCH_PROMPT_TEMPLATE = (
    "You are an expert mortgage underwriting condition analyst.\n\n"
    "You will be given two lists of underwriting conditions:\n"
    "- ENGINE: conditions generated by an automated system\n"
    "- UNDERWRITER: conditions created by a human underwriter in Encompass\n\n"
    "Your task is to semantically match conditions between the two lists.\n"
    "Two conditions MATCH if they refer to the same underlying requirement,\n"
    "even if worded very differently. For example:\n"
    '  - Engine: "Tri-Merge Credit Report Required" ≈ Underwriter: "Provide full credit report with all 3 bureaus"\n'
    '  - Engine: "Executed Lease Agreement Required" ≈ Underwriter: "Copy of signed lease needed"\n\n'
    "Be liberal in matching — if the core requirement is the same, it's a match.\n"
    "A single underwriter condition may match multiple engine conditions if they\n"
    "cover the same topic, and vice versa.\n\n"
    "Return ONLY valid JSON (no markdown, no explanation) with this structure:\n"
    '{\n'
    '  "matches": [\n'
    '    {\n'
    '      "engine_index": <0-based index>,\n'
    '      "engine_text": "<brief excerpt>",\n'
    '      "uw_index": <0-based index>,\n'
    '      "uw_text": "<brief excerpt>",\n'
    '      "confidence": <0.0-1.0>,\n'
    '      "reasoning": "<one sentence why they match>"\n'
    '    }\n'
    '  ],\n'
    '  "engine_only": [\n'
    '    {\n'
    '      "engine_index": <0-based index>,\n'
    '      "engine_text": "<brief excerpt>",\n'
    '      "reasoning": "<why no UW match>"\n'
    '    }\n'
    '  ],\n'
    '  "uw_only": [\n'
    '    {\n'
    '      "uw_index": <0-based index>,\n'
    '      "uw_text": "<brief excerpt>",\n'
    '      "reasoning": "<why no engine match>"\n'
    '    }\n'
    '  ]\n'
    '}\n'
)


def run_comparison(engine_conds: list[str], uw_conds: list[str]) -> dict:
    engine_numbered = "\n".join(
        f"  [{i}] {c}" for i, c in enumerate(engine_conds)
    )
    uw_numbered = "\n".join(
        f"  [{i}] {c}" for i, c in enumerate(uw_conds)
    )

    prompt = (
        _MATCH_PROMPT_TEMPLATE
        + "\nENGINE CONDITIONS:\n" + engine_numbered
        + "\n\nUNDERWRITER CONDITIONS:\n" + uw_numbered
    )

    client = Anthropic(api_key=os.environ["ANTHROPIC_API_KEY"])
    response = client.messages.create(
        model="claude-sonnet-4-20250514",
        max_tokens=8192,
        messages=[{"role": "user", "content": prompt}],
    )

    raw = response.content[0].text.strip()
    if raw.startswith("```"):
        raw = raw.split("\n", 1)[1]
        if raw.endswith("```"):
            raw = raw[: raw.rfind("```")]

    return json.loads(raw)


def compute_stats(
    result: dict,
    total_engine: int,
    total_uw: int,
) -> dict:
    matched_engine = set()
    matched_uw = set()
    for m in result.get("matches", []):
        matched_engine.add(m["engine_index"])
        matched_uw.add(m["uw_index"])

    tp = len(matched_uw)
    fp = total_engine - len(matched_engine)
    fn = total_uw - len(matched_uw)

    precision = tp / (tp + fp) if (tp + fp) > 0 else 0
    recall = tp / (tp + fn) if (tp + fn) > 0 else 0
    f1 = 2 * precision * recall / (precision + recall) if (precision + recall) > 0 else 0

    return {
        "total_engine": total_engine,
        "total_underwriter": total_uw,
        "matched_pairs": len(result.get("matches", [])),
        "engine_matched": len(matched_engine),
        "uw_matched": len(matched_uw),
        "engine_only": total_engine - len(matched_engine),
        "uw_only": total_uw - len(matched_uw),
        "precision": round(precision, 3),
        "recall": round(recall, 3),
        "f1": round(f1, 3),
        "avg_confidence": round(
            sum(m.get("confidence", 0) for m in result.get("matches", []))
            / max(len(result.get("matches", [])), 1),
            3,
        ),
    }


def main():
    if len(sys.argv) < 3:
        print("Usage: python verify_conditions.py <engine_output.json> <underwriter_conditions>")
        print("       underwriter_conditions can be .json or .txt")
        sys.exit(1)

    engine_path = Path(sys.argv[1])
    uw_path = Path(sys.argv[2])

    if not engine_path.exists():
        print(f"Error: {engine_path} not found")
        sys.exit(1)
    if not uw_path.exists():
        print(f"Error: {uw_path} not found")
        sys.exit(1)

    print(f"Loading engine conditions from: {engine_path}")
    engine_conds = _load_engine_conditions(engine_path)
    print(f"  → {len(engine_conds)} conditions")

    print(f"Loading underwriter conditions from: {uw_path}")
    uw_conds = _load_underwriter_conditions(uw_path)
    print(f"  → {len(uw_conds)} conditions")

    if not engine_conds:
        print("Error: No engine conditions found")
        sys.exit(1)
    if not uw_conds:
        print("Error: No underwriter conditions found")
        sys.exit(1)

    print("\nRunning semantic comparison via LLM...")
    result = run_comparison(engine_conds, uw_conds)

    stats = compute_stats(result, len(engine_conds), len(uw_conds))
    result["stats"] = stats

    print("\n" + "=" * 70)
    print("  VERIFICATION REPORT")
    print("=" * 70)

    print(f"\n  Engine conditions:      {stats['total_engine']}")
    print(f"  Underwriter conditions: {stats['total_underwriter']}")
    print(f"  Matched pairs:          {stats['matched_pairs']}")
    print(f"  Avg match confidence:   {stats['avg_confidence']}")

    print(f"\n  Engine-only (we found, UW didn't):   {stats['engine_only']}")
    print(f"  UW-only (UW found, we missed):       {stats['uw_only']}")

    print(f"\n  Precision: {stats['precision']:.1%}  (of our conditions, how many were real)")
    print(f"  Recall:    {stats['recall']:.1%}  (of UW conditions, how many we caught)")
    print(f"  F1 Score:  {stats['f1']:.1%}")

    if result.get("matches"):
        print(f"\n  {'─' * 66}")
        print(f"  MATCHED CONDITIONS ({len(result['matches'])})")
        print(f"  {'─' * 66}")
        for m in result["matches"]:
            conf = m.get("confidence", 0)
            bar = "█" * int(conf * 10) + "░" * (10 - int(conf * 10))
            print(f"\n  [{bar}] {conf:.0%}")
            print(f"    Engine [{m['engine_index']}]: {m['engine_text'][:80]}")
            print(f"    UW     [{m['uw_index']}]: {m['uw_text'][:80]}")
            if m.get("reasoning"):
                print(f"    Why: {m['reasoning']}")

    if result.get("uw_only"):
        print(f"\n  {'─' * 66}")
        print(f"  MISSED BY ENGINE ({len(result['uw_only'])})")
        print(f"  {'─' * 66}")
        for item in result["uw_only"]:
            print(f"\n    UW [{item['uw_index']}]: {item['uw_text'][:90]}")
            if item.get("reasoning"):
                print(f"    Why missed: {item['reasoning']}")

    if result.get("engine_only"):
        print(f"\n  {'─' * 66}")
        print(f"  ENGINE-ONLY / EXTRA ({len(result['engine_only'])})")
        print(f"  {'─' * 66}")
        for item in result["engine_only"]:
            print(f"\n    Engine [{item['engine_index']}]: {item['engine_text'][:90]}")
            if item.get("reasoning"):
                print(f"    Why extra: {item['reasoning']}")

    out_path = engine_path.stem + "_verify_report.json"
    with open(out_path, "w") as f:
        json.dump(result, f, indent=2, default=str)
    print(f"\n  Full report saved to: {out_path}")


if __name__ == "__main__":
    main()
