#!/usr/bin/env python3
"""
Generate registry.py from workflow_config.json.

Run from the project root:
    python config/generate.py
"""

import json
import os
import textwrap
from pathlib import Path

CONFIG_PATH = Path(__file__).parent / "workflow_config.json"
OUTPUT_PATH = Path(__file__).parent.parent / "registry.py"


def load_config() -> dict:
    with open(CONFIG_PATH) as f:
        return json.load(f)


def build_step_order(config: dict) -> list[str]:
    phases = sorted(config["phases"].items(), key=lambda kv: kv[1]["order"])
    order = []
    for _phase_name, phase in phases:
        for step_num in phase["steps"]:
            order.append(f"STEP_{step_num:02d}")
    return order


def render_registry(config: dict) -> str:
    step_order = build_step_order(config)
    general_tools = config["general_tools"]
    dev_mode = config.get("dev_mode", {})

    lines = [
        '"""',
        "registry.py — AUTO-GENERATED by config/generate.py",
        "DO NOT EDIT MANUALLY. Edit config/workflow_config.json and re-run generate.py.",
        '"""',
        "",
        "from __future__ import annotations",
        "",
        "import os",
        "from typing import Any",
        "",
        "",
        "# ---------------------------------------------------------------------------",
        "# Step configuration",
        "# ---------------------------------------------------------------------------",
        "",
        "STEP_CONFIG: dict[str, dict[str, Any]] = {",
    ]

    for step_id, step in config["steps"].items():
        substeps_repr = json.dumps(step["substeps"], indent=8)
        # indent by 4 for inside the dict
        substeps_indented = textwrap.indent(substeps_repr, "        ")
        # collect all tools from substeps (de-duped, preserving order)
        seen: set[str] = set()
        step_tools: list[str] = []
        for sub in step["substeps"]:
            for t in sub.get("tools", []):
                if t not in seen and t not in general_tools:
                    seen.add(t)
                    step_tools.append(t)

        lines.append(f'    "{step_id}": {{')
        lines.append(f'        "name": {json.dumps(step["name"])},')
        lines.append(f'        "description": {json.dumps(step["description"])},')
        lines.append(f'        "plan_file": {json.dumps(step["plan_file"])},')
        lines.append(f'        "tools": {json.dumps(step_tools)},')
        lines.append(f'        "substeps": {substeps_indented.strip()},')
        lines.append("    },")

    lines += [
        "}",
        "",
        "",
        "# ---------------------------------------------------------------------------",
        "# Step ordering (derived from phases)",
        "# ---------------------------------------------------------------------------",
        "",
        f"STEP_ORDER: list[str] = {json.dumps(step_order)}",
        "",
        "",
        "# ---------------------------------------------------------------------------",
        "# General tools — always available regardless of current step",
        "# ---------------------------------------------------------------------------",
        "",
        f"GENERAL_TOOL_NAMES: list[str] = {json.dumps(general_tools)}",
        "",
        "",
        "# ---------------------------------------------------------------------------",
        "# Dev mode — controlled by config, env vars, or input state",
        "# ---------------------------------------------------------------------------",
        "",
        "_DEFAULT_DEV_MODE: dict[str, Any] = " + repr(dev_mode),
        "",
        "",
        "def get_dev_mode(input_state: dict | None = None) -> dict[str, Any]:",
        '    """',
        "    Resolve dev mode config.",
        "    Priority: input_state > env vars > config defaults.",
        '    """',
        "    mode = dict(_DEFAULT_DEV_MODE)",
        "",
        "    # Override from environment variables",
        '    if os.environ.get("DEV_MODE_ENABLED", "").lower() in ("1", "true", "yes"):',
        '        mode["enabled"] = True',
        '    if os.environ.get("DEV_MODE_SKIP_STEPS"):',
        '        mode["skip_steps"] = os.environ["DEV_MODE_SKIP_STEPS"].split(",")',
        '    if os.environ.get("DEV_MODE_CUTOFF_STEP"):',
        '        mode["cutoff_step"] = os.environ["DEV_MODE_CUTOFF_STEP"]',
        "",
        "    # Override from input state (highest priority)",
        "    if input_state:",
        '        state_dev = input_state.get("dev_mode") or {}',
        "        mode.update(state_dev)",
        "",
        "    return mode",
        "",
        "",
        "def is_step_skipped(step_id: str, input_state: dict | None = None) -> bool:",
        '    """Return True if this step should be skipped in dev mode."""',
        "    dev = get_dev_mode(input_state)",
        '    if not dev.get("enabled"):',
        "        return False",
        '    if step_id in (dev.get("skip_steps") or []):',
        "        return True",
        '    cutoff = dev.get("cutoff_step")',
        "    if cutoff and STEP_ORDER.index(step_id) > STEP_ORDER.index(cutoff):",
        "        return True",
        "    return False",
        "",
        "",
        "def get_step_tools(step_id: str) -> list[str]:",
        '    """Return the tool names registered for a given step."""',
        "    return STEP_CONFIG.get(step_id, {}).get(\"tools\", [])",
        "",
        "",
        "def get_step_plan_file(step_id: str) -> str | None:",
        '    """Return the plan markdown filename for a given step."""',
        "    return STEP_CONFIG.get(step_id, {}).get(\"plan_file\")",
        "",
        "",
        "def get_current_step(state: dict) -> str | None:",
        '    """Extract the current step from agent state."""',
        '    return state.get("current_step")',
    ]

    return "\n".join(lines) + "\n"


def main() -> None:
    config = load_config()
    content = render_registry(config)
    OUTPUT_PATH.write_text(content)
    print(f"Generated: {OUTPUT_PATH}")


if __name__ == "__main__":
    main()
