"""
assets_tools.py — Tools for STEP_03: Assets & Reserves Conditions Engine.
"""

from __future__ import annotations

from langchain_core.tools import InjectedToolArg, tool
from langgraph.types import Command
from typing_extensions import Annotated


@tool
def generate_asset_conditions(
    conditions: list[dict],
    state: Annotated[dict, InjectedToolArg] = None,
) -> Command:
    """
    Store the assets and reserves conditions generated by the LLM.

    The LLM calls this tool after reasoning over the scenario_summary asset_profile,
    the docs_by_facet.assets documents, and the loaded guideline sections.

    Args:
        conditions: List of condition dicts conforming to the standard condition schema.
    """
    for c in conditions:
        if "tags" not in c:
            c["tags"] = []
        if "assets" not in c["tags"]:
            c["tags"].append("assets")

    return Command(update={
        "module_outputs": {"03": {"conditions": conditions}},
        "current_step": "STEP_03",
    })
