"""
compliance_tools.py — Tools for STEP_07: Compliance Conditions Engine.
"""

from __future__ import annotations

from langchain_core.tools import InjectedToolArg, tool
from langgraph.types import Command
from typing_extensions import Annotated


@tool
def generate_compliance_conditions(
    conditions: list[dict],
    state: Annotated[dict, InjectedToolArg] = None,
) -> Command:
    """
    Store the compliance conditions generated by the LLM.

    The LLM calls this tool after reasoning over the scenario_summary (borrowers,
    occupancy, program), the docs_by_facet.compliance documents, and the loaded
    guideline sections.

    Args:
        conditions: List of condition dicts conforming to the standard condition schema.
    """
    for c in conditions:
        if "tags" not in c:
            c["tags"] = []
        if "compliance" not in c["tags"]:
            c["tags"].append("compliance")

    return Command(update={
        "module_outputs": {"07": {"conditions": conditions}},
        "current_step": "STEP_07",
    })
