"""
credit_tools.py — Tools for STEP_04: Credit Conditions Engine.
"""

from __future__ import annotations

from langchain_core.tools import InjectedToolArg, tool
from langgraph.types import Command
from typing_extensions import Annotated


@tool
def generate_credit_conditions(
    conditions: list[dict],
    state: Annotated[dict, InjectedToolArg] = None,
) -> Command:
    """
    Store the credit conditions generated by the LLM.

    The LLM calls this tool after reasoning over the scenario_summary credit section,
    the docs_by_facet.credit documents, and the loaded guideline sections.

    Args:
        conditions: List of condition dicts conforming to the standard condition schema.
    """
    for c in conditions:
        if "tags" not in c:
            c["tags"] = []
        if "credit" not in c["tags"]:
            c["tags"].append("credit")

    return Command(update={
        "module_outputs": {"04": {"conditions": conditions}},
        "current_step": "STEP_04",
    })
