"""
income_tools.py — Tools for STEP_02: Income Conditions Engine.

Generates income-only conditions per the plan in step_02_income.md.
"""

from __future__ import annotations

from langchain_core.tools import InjectedToolArg, tool
from langgraph.types import Command
from typing_extensions import Annotated

from tools.shared.guidelines import load_sections


@tool
def load_guideline_sections(
    section_names: list[str],
    state: Annotated[dict, InjectedToolArg] = None,
) -> str:
    """
    Load NQMF guideline content for the given section names.
    Returns the text content to be used as context by the LLM.

    Args:
        section_names: List of guideline section headings to load.
    """
    return load_sections(section_names)


@tool
def generate_income_conditions(
    conditions: list[dict],
    state: Annotated[dict, InjectedToolArg] = None,
) -> Command:
    """
    Store the income conditions generated by the LLM.

    The LLM calls this tool after reasoning over the scenario_summary income_profile,
    the docs_by_facet.income documents, and the loaded guideline sections.

    Args:
        conditions: List of condition dicts conforming to the standard condition schema.
    """
    for c in conditions:
        if "tags" not in c:
            c["tags"] = []
        if "income" not in c["tags"]:
            c["tags"].append("income")

    return Command(update={
        "module_outputs": {"02": {"conditions": conditions}},
        "current_step": "STEP_02",
    })
