"""
masterlist_tools.py — Match engine-generated conditions to the official
conditions masterlist (Encompass condition library).

After the engine generates free-form conditions (STEP_01-08) and they are
merged/ranked (STEP_09), this tool semantically matches each engine condition
to the closest entry in the official masterlist.  Only masterlist-backed
conditions appear in the final output, ensuring consistent wording and
traceability.
"""

from __future__ import annotations

import json
import os
from pathlib import Path
from typing import Any

from langchain_core.messages import ToolMessage
from langchain_core.tools import InjectedToolCallId, tool
from langgraph.prebuilt import InjectedState
from langgraph.types import Command
from typing_extensions import Annotated

_MASTERLIST_PATH = Path(__file__).parent.parent / "data" / "conditions_masterlist.json"

# Engine category → masterlist category candidates (kept focused to avoid
# overwhelming the LLM with too many candidates per call).
_CATEGORY_MAP: dict[str, list[str]] = {
    "Credit": ["Credit"],
    "Income": ["Income"],
    "Assets": ["Assets"],
    "Property": ["Property"],
    "Title": ["Legal"],
    "Compliance": ["Legal"],
    "Program Eligibility": ["Misc", "Credit"],
    "Other": ["Misc"],
    "Document Completeness": [],
}


def _load_masterlist() -> list[dict]:
    with open(_MASTERLIST_PATH, encoding="utf-8") as f:
        data = json.load(f)
    return data.get("conditions", [])


def _build_category_index(masterlist: list[dict]) -> dict[str, list[dict]]:
    idx: dict[str, list[dict]] = {}
    for entry in masterlist:
        cat = entry.get("category", "")
        idx.setdefault(cat, []).append(entry)
    return idx


def _format_candidates(candidates: list[dict], max_items: int = 250) -> str:
    lines = []
    for i, c in enumerate(candidates[:max_items]):
        title = c.get("title", "")
        desc = (c.get("description", "") or "")[:150]
        mc_id = c.get("id", "")
        text = f"  [{mc_id}] {title}"
        if desc:
            text += f" — {desc}"
        lines.append(text)
    return "\n".join(lines)


def _format_engine_conditions(conditions: list[dict]) -> str:
    lines = []
    for i, c in enumerate(conditions):
        title = c.get("title", "")
        desc = (c.get("description", "") or "")[:200]
        cat = c.get("category", "")
        sev = c.get("severity", "")
        lines.append(f"  [E{i}] [{cat}/{sev}] {title}: {desc}")
    return "\n".join(lines)


_MATCH_PROMPT = (
    "You are an expert mortgage underwriting condition analyst.\n\n"
    "You will be given ENGINE conditions generated by an automated system "
    "and a MASTERLIST of official Encompass conditions.\n\n"
    "For EACH engine condition, find the BEST matching masterlist condition. "
    "Two conditions match if they address the same underlying requirement, "
    "even if worded differently.\n\n"
    "Rules:\n"
    "- Each engine condition should match AT MOST one masterlist condition\n"
    "- Multiple engine conditions CAN match the same masterlist condition\n"
    "- If no masterlist condition is a reasonable match, mark it as unmatched\n"
    "- Be liberal: if the core requirement overlaps, it's a match\n"
    "- Confidence must be >= 0.6 to count as a match\n\n"
    "Return ONLY valid JSON (no markdown, no explanation):\n"
    '[\n'
    '  {\n'
    '    "engine_index": <int>,\n'
    '    "masterlist_id": "<MC-XXXX or null if unmatched>",\n'
    '    "confidence": <0.0-1.0>,\n'
    '    "reasoning": "<one sentence>"\n'
    '  }\n'
    ']\n'
)


def _call_llm_match(
    engine_text: str, candidates_text: str, model: str = "claude-sonnet-4-20250514"
) -> list[dict]:
    """Call Claude to semantically match engine conditions to masterlist."""
    from anthropic import Anthropic

    prompt = (
        _MATCH_PROMPT
        + "\nENGINE CONDITIONS:\n" + engine_text
        + "\n\nMASTERLIST CANDIDATES:\n" + candidates_text
    )

    client = Anthropic(api_key=os.environ.get("ANTHROPIC_API_KEY", ""))
    response = client.messages.create(
        model=model,
        max_tokens=16384,
        messages=[{"role": "user", "content": prompt}],
    )

    raw = response.content[0].text.strip()
    if raw.startswith("```"):
        raw = raw.split("\n", 1)[1] if "\n" in raw else raw[3:]
        if raw.endswith("```"):
            raw = raw[:-3]
        raw = raw.strip()

    return json.loads(raw)


def _is_channel_excluded(ml_entry: dict, channel: str) -> bool:
    """Exclude masterlist conditions whose title prefix doesn't match the loan channel."""
    title = (ml_entry.get("title") or "").strip()
    ch = channel.lower()
    if title.startswith("CORR:") or title.startswith("CORR "):
        return ch not in ("correspondent", "corr")
    if title.startswith("DPA ") or title.startswith("DPA:"):
        return "dpa" not in ch and "down payment" not in ch
    return False


def run_masterlist_matching(
    ranked: list[dict],
    scenario_summary: dict | None = None,
) -> dict:
    """
    Core matching logic — called programmatically from generate_final_output.

    For each engine condition:
    1. Pre-filter masterlist candidates by category mapping and channel
    2. Use LLM to find the best semantic match
    3. Replace the engine condition with the official masterlist version,
       preserving the engine's severity and priority
    4. Post-filter: use engine description (scenario-aware) when masterlist
       description is generic

    Returns a dict with matched_conditions, unmatched_conditions,
    passthrough_conditions, and match_stats.
    """
    ss = scenario_summary or {}

    if not ranked:
        return {
            "matched_conditions": [],
            "unmatched_conditions": [],
            "passthrough_conditions": [],
            "match_stats": {},
        }

    masterlist = _load_masterlist()

    # Pre-filter masterlist by channel
    channel = ss.get("channel", "") or ""
    if channel:
        masterlist = [m for m in masterlist if not _is_channel_excluded(m, channel)]

    cat_index = _build_category_index(masterlist)
    ml_by_id = {c["id"]: c for c in masterlist}

    passthrough: list[dict] = []
    to_match: list[dict] = []

    for cond in ranked:
        cat = cond.get("category", "Other")
        if cat == "Document Completeness":
            passthrough.append(cond)
        else:
            to_match.append(cond)

    if not to_match:
        return {
            "matched_conditions": [],
            "unmatched_conditions": [],
            "passthrough_conditions": passthrough,
            "match_stats": {"passthrough": len(passthrough)},
        }

    # Group engine conditions by their ENGINE category so each LLM call
    # gets a focused set of conditions and candidates.
    eng_cat_groups: dict[str, list[tuple[int, dict]]] = {}
    for i, cond in enumerate(to_match):
        eng_cat = cond.get("category", "Other")
        eng_cat_groups.setdefault(eng_cat, []).append((i, cond))

    all_matches: dict[int, dict] = {}

    for eng_cat, group_items in eng_cat_groups.items():
        ml_cat_names = _CATEGORY_MAP.get(eng_cat, ["Misc", "Legal"])
        candidates: list[dict] = []
        for cat_name in ml_cat_names:
            candidates.extend(cat_index.get(cat_name, []))

        if not candidates:
            continue

        engine_conds = [item[1] for item in group_items]
        engine_text = _format_engine_conditions(engine_conds)
        candidates_text = _format_candidates(candidates)

        try:
            matches = _call_llm_match(engine_text, candidates_text)
        except Exception as exc:
            import sys
            print(f"  [masterlist] LLM match failed for {eng_cat}: {exc}", file=sys.stderr)
            continue

        for m in matches:
            eng_idx_local = m.get("engine_index", -1)
            if eng_idx_local < 0 or eng_idx_local >= len(group_items):
                continue
            orig_idx = group_items[eng_idx_local][0]
            all_matches[orig_idx] = m

    matched_conditions: list[dict] = []
    unmatched_conditions: list[dict] = []

    for i, cond in enumerate(to_match):
        match_info = all_matches.get(i)
        ml_id = match_info.get("masterlist_id") if match_info else None
        confidence = match_info.get("confidence", 0) if match_info else 0

        if ml_id and ml_id in ml_by_id and confidence >= 0.6:
            ml_entry = ml_by_id[ml_id]
            ml_desc = (ml_entry.get("description") or "").strip()
            eng_desc = (cond.get("description") or "").strip()
            # Always prefer the engine description — it is scenario-aware and
            # tailored to the specific loan.  Fall back to masterlist only if
            # the engine produced nothing.
            description = eng_desc if eng_desc else ml_desc

            matched_cond = {
                "masterlist_id": ml_id,
                "masterlist_title": ml_entry["title"],
                "masterlist_description": ml_desc,
                "masterlist_category": ml_entry.get("category", ""),
                "for_role": ml_entry.get("for_role", ""),
                "allow_to_clear": ml_entry.get("allow_to_clear"),
                "prior_to": ml_entry.get("prior_to", ""),
                "masterlist_documents": ml_entry.get("documents", ""),
                "title": ml_entry["title"],
                "description": description,
                "category": cond.get("category", "Other"),
                "severity": cond.get("severity", "SOFT-STOP"),
                "priority": cond.get("priority", "P3"),
                "required_documents": cond.get("required_documents", []),
                "required_data_elements": cond.get("required_data_elements", []),
                "match_confidence": confidence,
                "match_reasoning": match_info.get("reasoning", ""),
                "engine_title": cond.get("title", ""),
                "engine_description": eng_desc,
            }
            matched_conditions.append(matched_cond)
        else:
            unmatched_cond = dict(cond)
            unmatched_cond["masterlist_id"] = None
            unmatched_cond["match_confidence"] = confidence
            unmatched_cond["match_reasoning"] = (
                match_info.get("reasoning", "No suitable match found")
                if match_info else "No suitable match found"
            )
            unmatched_conditions.append(unmatched_cond)

    match_stats = {
        "total_engine": len(ranked),
        "passthrough": len(passthrough),
        "attempted_match": len(to_match),
        "matched": len(matched_conditions),
        "unmatched": len(unmatched_conditions),
        "match_rate": (
            f"{len(matched_conditions)/len(to_match)*100:.1f}%"
            if to_match else "N/A"
        ),
    }

    return {
        "matched_conditions": matched_conditions,
        "unmatched_conditions": unmatched_conditions,
        "passthrough_conditions": passthrough,
        "match_stats": match_stats,
    }


@tool
def match_to_masterlist(
    tool_call_id: Annotated[str, InjectedToolCallId] = "",
    state: Annotated[dict, InjectedState] = None,
) -> Command:
    """
    Match ranked engine conditions against the official conditions masterlist.
    This is also called automatically by generate_final_output, so calling
    it explicitly is optional.
    """
    s = state or {}
    mo = s.get("module_outputs", {})
    ranked = mo.get("09_rank", {}).get("ranked_conditions", [])
    if not ranked:
        ranked = mo.get("09_merge", {}).get("merged_conditions", [])

    result = run_masterlist_matching(ranked, s.get("scenario_summary"))
    stats = result.get("match_stats", {})
    matched = result.get("matched_conditions", [])
    unmatched = result.get("unmatched_conditions", [])
    passthrough = result.get("passthrough_conditions", [])

    msg = (
        f"Masterlist matching: {len(matched)} matched, "
        f"{len(unmatched)} unmatched, "
        f"{len(passthrough)} passthrough. "
        f"Match rate: {stats.get('match_rate', 'N/A')}."
    )

    return Command(update={
        "module_outputs": {"09_masterlist": result},
        "messages": [ToolMessage(msg, tool_call_id=tool_call_id)],
    })
