"""
property_tools.py — Tools for STEP_05: Property & Appraisal Conditions Engine.
"""

from __future__ import annotations

from langchain_core.tools import InjectedToolArg, tool
from langgraph.types import Command
from typing_extensions import Annotated


@tool
def generate_property_conditions(
    conditions: list[dict],
    state: Annotated[dict, InjectedToolArg] = None,
) -> Command:
    """
    Store the property and appraisal conditions generated by the LLM.

    The LLM calls this tool after reasoning over the scenario_summary property section,
    the docs_by_facet.property_appraisal documents, and the loaded guideline sections.

    Args:
        conditions: List of condition dicts conforming to the standard condition schema.
    """
    for c in conditions:
        if "tags" not in c:
            c["tags"] = []
        for tag in ("property", "appraisal"):
            if tag not in c["tags"]:
                c["tags"].append(tag)

    return Command(update={
        "module_outputs": {"05": {"conditions": conditions}},
        "current_step": "STEP_05",
    })
