"""
title_tools.py — Tools for STEP_06: Title & Closing Conditions Engine.
"""

from __future__ import annotations

from langchain_core.tools import InjectedToolArg, tool
from langgraph.types import Command
from typing_extensions import Annotated


@tool
def generate_title_conditions(
    conditions: list[dict],
    state: Annotated[dict, InjectedToolArg] = None,
) -> Command:
    """
    Store the title and closing conditions generated by the LLM.

    The LLM calls this tool after reasoning over the scenario_summary (purpose, property,
    loan_terms), the docs_by_facet.title_closing documents, and the loaded guideline sections.

    Args:
        conditions: List of condition dicts conforming to the standard condition schema.
    """
    for c in conditions:
        if "tags" not in c:
            c["tags"] = []
        for tag in ("title", "closing"):
            if tag not in c["tags"]:
                c["tags"].append(tag)

    return Command(update={
        "module_outputs": {"06": {"conditions": conditions}},
        "current_step": "STEP_06",
    })
